### ISSUE TITLE
Calculation eg total cost steel

### ISSUE THREAD

**Issue by dirkforke** [Deschain53/Sim_Company_Web_Calculator#1]
1. I love your tool! Thanks.
2. No problem but maybe you haven‘t seen what happens sometimes with calculation. Looks like you have to mask. 

![717ABC1F-F810-4C32-9AB8-8ACBBF5224B2](https://user-images.githubusercontent.com/45095400/163923808-ff92b66f-71ab-4e36-8578-e29e93cbbda4.jpeg)

**Comment by Deschain53** [comment]
Hi, thanks for your comment. I'll fix the bug it in the next update. If you see another bug please let me know because I don't play anymore so I don't use it.

**Comment by dirkforke** [comment]
thanks
